export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';

export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST';
export const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE';
export const FETCH_CURRENT_USER_REQUEST = 'FETCH_CURRENT_USER_REQUEST';
export const FETCH_CURRENT_USER_SUCCESS = 'FETCH_CURRENT_USER_SUCCESS';
export const FETCH_CURRENT_USER_FAILURE = 'FETCH_CURRENT_USER_FAILURE';

export const LOCALE_SET = 'LOCALE_SET';
export const THEME_SET = 'THEME_SET';
export const BOOKS_FETCHED = 'BOOKS_FETCHED';
export const BOOKS_CREATED = 'BOOKS_CREATED';
export const SPONSORS_FETCHED = 'SPONSORS_FETCHED';
export const SPONSORS_CREATED = 'SPONSORS_CREATED';
